### ISSUE TITLE
Flashlight on Models Breaks Lighting for Them

### ISSUE THREAD

**Issue by Gocnak** [thexa4/source-pbr#12]
Hi,

The shader does really well except for when using the flashlight on a model. At certain angles, the lighting on the model seems to change to only be the flashlight or something? It's believed that perhaps the lighting origin is changing for the model. Not sure what's up.

Here's a gfycat of it happening:
https://gfycat.com/adorablepassionatechipmunk

**Comment by thexa4** [comment]
Thanks for the report! This is a known issue but so far we don't know what is causing it exactly.

Somehow using a flashlight sometimes affects dynamic lighting, cubemaps and ambient cubes. It might have something to do with using the player? origin instead of the model origin for lighting.

**Comment by bonjorno7** [comment]
You can change the model's origin without changing the player's origin, just turning your camera is enough.
Example: https://gfycat.com/tidyhandyclingfish

**Comment by YuRaNnNzZZ** [comment]
Translucency is kinda broken with flashlights too.
https://yurie.thigh-high.club/3p8c4we8.mp4
