### ISSUE TITLE
Adding any kind of transparency to the material breaks it

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [thexa4/source-pbr#13]
Using $translucent or $alphatest in a PBR material makes it invisible.

![](https://user-images.githubusercontent.com/5104603/68765763-9bc71800-062e-11ea-8399-91767fdfc506.png)
After adding `$translucent "1"` or `$alphatest "1"`:
![](https://user-images.githubusercontent.com/5104603/68765777-a386bc80-062e-11ea-86cf-ebba5912f075.png)

And it's not a problem with the texture itself, here's the same material but with VertexLitGeneric shader and `$translucent "1"`:
![](https://user-images.githubusercontent.com/5104603/68765849-cb762000-062e-11ea-9a6c-58db00aa8565.png)

**Comment by thexa4** [comment]
Thanks for the bug report. Do you get any warnings / errors in the console?

**Comment by YuRaNnNzZZ** [comment]
No errors or warnings in there, unfortunately.

**Comment by YuRaNnNzZZ** [comment]
Alright, so i think i've found the cause of the issue.
Removing `* g_BaseColor` part from [this line in fxc file](https://github.com/thexa4/source-pbr/blob/feature/pbr-base/mp/src/materialsystem/stdshaders/pbr_ps30.fxc#L244) makes transparency work as intended:
![](https://yurie.thigh-high.club/j1magcvr.png)
![](https://yurie.thigh-high.club/lq7btm83.png)

For some reason it discards the alpha value when multiplying by "base color" which is selfillum one? (according to PSREG variable name)

EDIT: Of course, it's multiplying vector4 by Vector, which has no 4th value.
