### ISSUE TITLE
Physics props lose their ambient lighting after freezing

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [thexa4/source-pbr#14]
As described in the title, the `prop_physics` entities lose their color data [when they are not moving](https://yurie.thigh-high.club/2h9m75tc.mp4).

On the left is model with `$CollisionModel` added, and on the right is a model without collision:
![](https://yurie.thigh-high.club/8yhhn1je.png)
![](https://yurie.thigh-high.club/12w4csz6.png)

(tested on two different maps with correct lighting and cubemaps)

**Comment by thexa4** [comment]
Interesting. Is this an issue specific to PBR?

**Comment by YuRaNnNzZZ** [comment]
Yes, this doesn't happen with VertexLitGeneric props.

**Comment by YuRaNnNzZZ** [comment]
When physics props are in sleeping state, it seems that they are only receiving lighting from projected textures and dynamic lights
![](https://yurie.thigh-high.club/jpgjkt5e.jpg)
![](https://yurie.thigh-high.club/m21f4k3r.jpg)
![](https://yurie.thigh-high.club/c48635tn.jpg)

**Comment by YuRaNnNzZZ** [comment]
And this issue is not limited to one specific game, i can reproduce it in the latest stable version of Empires as well:
![](https://yurie.thigh-high.club/e7i3e6mz.png)
