### ISSUE TITLE
$basetexturetransform is nonfunctional

### ISSUE THREAD

**Issue by chanoc1** [thexa4/source-pbr#23]
$basetexturetransform is nonfunctional, it doesn't seem to do anything to the basetexture.

**Comment by YuRaNnNzZZ** [comment]
https://github.com/thexa4/source-pbr/blob/a5811c3c9f665dc6a07548b91cab876cf6f49a14/mp/src/materialsystem/stdshaders/pbr_vs20b.fxc#L111-L114
https://github.com/thexa4/source-pbr/blob/a5811c3c9f665dc6a07548b91cab876cf6f49a14/mp/src/materialsystem/stdshaders/pbr_vs30.fxc#L106-L109

i wonder why...
