### ISSUE TITLE
Prop_Static does not render correctly.

### ISSUE THREAD

**Issue by TobyMaddix** [thexa4/source-pbr#26]
The pbr shader only seems to work right on prop_dynamic, prop_static will only give off a convincing pbr effect when an env_projectedtexture is used.
![shadertest0000](https://user-images.githubusercontent.com/25801673/77218265-6755f200-6b21-11ea-98ce-d5a1a9a6f29c.jpg)
Flashlight off ^^
![shadertest0001](https://user-images.githubusercontent.com/25801673/77218269-7177f080-6b21-11ea-88ef-66af0367dcee.jpg)
Flashlight on ^^

**Comment by bonjorno7** [comment]
This is fixed by adding a few more flags in the cpp. Already done in https://github.com/thexa4/source-pbr/pull/25

**Comment by TobyMaddix** [comment]
You mean the shader’s .cpp file? just to confirm.

**Comment by bonjorno7** [comment]
Yeah, material flags2:
https://github.com/thexa4/source-pbr/commit/196945507330f38f337e0f15fb19f863db92134f
and
https://github.com/thexa4/source-pbr/commit/2d0f2c2640bd9537d40f417ead823d4434b7d18f
should shed some light

**Comment by TobyMaddix** [comment]
Fixed it, thanks!
