### ISSUE TITLE
Parallax is broken after the flashlight/projected texture fix got implemented

### ISSUE THREAD

**Issue by Bsodman1** [thexa4/source-pbr#32]
From what I see the speculars from a projected texture draw correctly, but the diffuse is all broken, it's drawn at the lowest point of the parallax depth, with no parallax effect applied.
Image has Lightmappedgeneric on the right, PBR on the left with a projected texture pointing at the ground.

![PBR parallax issue](https://user-images.githubusercontent.com/20006988/94867004-a81fb380-0440-11eb-95fe-4bd7e1d72046.png)

**Comment by sears2424** [comment]
Can you try again using the updated binaries?

**Comment by thexa4** [comment]
Marking as closed, if you still have issues feel free to reopen this.
