### ISSUE TITLE
SP branch crash due to an unsupported register

### ISSUE THREAD

**Issue by untodesu** [thexa4/source-pbr#33]
It crashes when you do `mat_reloadallmaterials`

The reason is that Source 2013SP does not support registers higher than `c31` while this shader uses hardcoded `c40`.  
Changing it to generally free `c27` fixes everything.

**Comment by YuRaNnNzZZ** [comment]
i suggest making a PR to this repo


> Changing it to generally free `c27` fixes everything.

this fixed the crash on level change in GMod, thank you!

**Comment by untodesu** [comment]
Well I guess #34 fixed this...
