### ISSUE TITLE
Undeclared Identifiers in pbr_dx9.cpp

### ISSUE THREAD

**Issue by JeBobs** [thexa4/source-pbr#7]
when trying to build the game on Windows 10, I get this error in the build:

'3>d:\game projects\source sdk 2013 pbr\mp\src\materialsystem\stdshaders\pbr_dx9.cpp(251): error C2039: 'SetUSEENVAMBIENT' : is not a member of 'pbr_ps30_Static_Index'
3>          d:\game projects\source sdk 2013 pbr\mp\src\materialsystem\stdshaders\fxctmp9\pbr_ps30.inc(3) : see declaration of 'pbr_ps30_Static_Index'
3>d:\game projects\source sdk 2013 pbr\mp\src\materialsystem\stdshaders\pbr_dx9.cpp(252): error C2039: 'SetEMISSIVE' : is not a member of 'pbr_ps30_Static_Index'
3>          d:\game projects\source sdk 2013 pbr\mp\src\materialsystem\stdshaders\fxctmp9\pbr_ps30.inc(3) : see declaration of 'pbr_ps30_Static_Index'
3>d:\game projects\source sdk 2013 pbr\mp\src\materialsystem\stdshaders\pbr_dx9.cpp(253): error C2065: 'psh_forgot_to_set_static_CONVERT_TO_SRGB' : undeclared identifier'

I have successfully built the official SDK before, so I know that my config is not an issue.

**Comment by thexa4** [comment]
I think it can be resolved by building the shader using ./buildhl2mpshaders
If you still have issues after compiling, I'll try to commit a fixed version within 24 hours.
