### ISSUE TITLE
Grab a programmer!

### ISSUE THREAD

**Issue by 3DL1N** [thexa4/source-pbr#8]
Hey. I tried to transfer your PBR to my project with a few corrections. Everything was successfully compiled. The game complains of an error and does not show the texture. Materials for PBR prepared.

**Comment by 3DL1N** [comment]
Material does not support vertex format used by the mesh (maybe missing fields or mismatched vertex compression?), mesh will not be rendered. Grab a programmer!

**Comment by thexa4** [comment]
Are you using it for a model or for a brush? Could you paste your vmt contents here?

**Comment by 3DL1N** [comment]
I tried to write this with an analogy of your vmt on "wiki.empiresmod.com/PBR".
Additionally, I tried to take the last commit from here:
github.com/bonjorno7/source-pbr/commits/feature/pbr-base
"PBR"
{
	// Original shader: VertexLitGeneric
	$Albedo "models/Weapons/V_physics_gun/hull_diffuse"
    $Normal "models/Weapons/V_physics_gun/hull_norm"
	$Mrao   	"models/Weapons/V_physics_gun/hull_mrao"
	$envmap      	"env_cubemap"
	$surfaceprop   	"metal"
}

**Comment by thexa4** [comment]
Bonjorno's repo does not have the latest changes from this repo: https://github.com/thexa4/source-pbr/network

If you previously used VertexLitGeneric you want to add `$model 1` to your vmt.

**Comment by 3DL1N** [comment]
Hmm, it really worked with this parameter. Only now the texture is all white.

**Comment by bonjorno7** [comment]
Yeah uh don't use my branch. Also your VMT is all wrong. It's $basetexture, not $albedo. It's $normaltexture or $bumpmap (both work, choose one), not $normal. It's $mraotexture, not $mrao. With those changes it should work, good luck.

**Comment by 3DL1N** [comment]
Really))
I did not notice this myself))
Well, it works, but with an emo-grid :D
