### ISSUE TITLE
Bumpmap

### ISSUE THREAD

**Issue by 3DL1N** [thexa4/source-pbr#9]
Houston we have a problem. Bumpmap does not want to work on the new shader. What the problem is is not clear.
Checked both $normaltexture and $bumpmap. Nothing works. Models remain smooth.

**Comment by thexa4** [comment]
Would you mind attaching your model, vtfs, vmts and a small vmt to test them with?

**Comment by 3DL1N** [comment]
@thexa4 https://drive.google.com/file/d/12Fr5qv6mmD-cB4nurFzd7hTeov-fYCMR/view?usp=sharing
Here is the link, there is a model and material.

**Comment by thexa4** [comment]
On a quick scan of the vmt I can't find any issues that could cause the normal to not display. I will investigate this weekend.

**Comment by 3DL1N** [comment]
Greetings! Is there any progress?

**Comment by thexa4** [comment]
Sorry, life got in the way. I'll try looking at it in 24 hours.

**Comment by thexa4** [comment]
Thanks for your report. It's an issue with the code, not with your material.

I'll release a fixed version when I can but if you want to work around this in the meantime:
 - Edit pbr_dx9.cpp line 149, change info.normalTexture to info.bumpMap twice.
 - Edit pbr_dx9.cpp line 304, change info.normalTexture to info.bumpMap once.
